[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build_cli]
args = ["build", "-p", "gfx-ssl-v2-cli"]
command = "cargo"

[tasks.build_cli_release]
args = ["build", "-p", "gfx-ssl-v2-cli", "--release"]
command = "cargo"

[tasks.build_sdk]
args = ["build", "-p", "gfx-ssl-v2-sdk"]
command = "cargo"

