[config]
default_to_workspace = false
skip_core_tasks = true

[env.linux]
LD_LIBRARY_PATH = "./lib/linux/x86_64:$LD_LIBRARY_PATH"

[env.mac_intel]
LD_LIBRARY_PATH = "./lib/darwin/x86_64:$LD_LIBRARY_PATH"

[env.mac_arm]
LD_LIBRARY_PATH = "./lib/darwin/arm64:$LD_LIBRARY_PATH"

[tasks.build_cli]
args = ["build", "-p", "gfx-ssl-v2-cli"]
command = "cargo"

[tasks.build_cli_release]
args = ["build", "-p", "gfx-ssl-v2-cli", "--release"]
command = "cargo"

[tasks.build_sdk]
args = ["build", "-p", "gfx-ssl-v2-sdk"]
command = "cargo"

